[project]
name = "repl-nix-hypercover"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "linkedin-api>=2.3.1",
    "requests>=2.32.3",
]
